[package]
name = "upt-converter-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
serde = "1.0"
serde_json = "1.0"
utf16string = "0.2"
anyhow = "1.0.89"
upt-converter = { version = "0.1.0", path = "../upt-converter"}